name: Manual Install Test

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
      
    - name: Install Simple from Current Branch
      run: > 
        curl -o- https://raw.githubusercontent.com/johnlindquist/simplescripts/${GITHUB_REF##*/}/config/install.sh | 
        SIMPLE_PATH=~/.simple sh 
        
    - name: Create a Test Script
      run: >
        source ~/.simple/.simplerc &&
        new running-test-template --template test
        
    - name: Run the Test Script
      run: >
        source ~/.simple/.simplerc &&
        running-test-template
