name: Manual Install Test

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Extract Branch Name
      uses: rlespinasse/github-slug-action@3.1.0
      
    - name: Log Branch Name
      run: echo "Running install from ${{ env.GITHUB_REF_SLUG }}"
      
    - name: Install Simple from Current Branch
      run: > 
        curl -o- https://raw.githubusercontent.com/johnlindquist/simplescripts/${{ env.GITHUB_REF_SLUG }}/config/install.sh | 
        SIMPLE_PATH=~/.simple sh 
        
    - name: Create a Test Script
      run: >
        source ~/.simple/.simplerc &&
        new running-test-template --template test
        
    - name: Run the Test Script
      run: >
        source ~/.simple/.simplerc &&
        running-test-template
