name: Manual Install Test

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Install Simple
      run: > 
        curl -o- https://simplescripts.dev/api/install | 
        SIMPLE_PATH=~/.simple sh 
        
    - name: Create a Test Script
      run: >
        source ~/.simple/.simplerc &&
        new running-test-template --template test
    - name: Run the Test Script
      run: >
        source ~/.simple/.simplerc &&
        running-test-template
