name: Manual Install Test

on:
  workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Install Simple Scripts
      run: curl -o- https://simplescripts.dev/api/install | SIMPLE_PATH=~/.simple sh && source ~/.simple/.simplerc
