name: Manual Install Test

on:
  workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Install Simple
      run: > 
        curl -o- https://simplescripts.dev/api/install | 
        SIMPLE_PATH=~/.simple sh && 
        source ~/.simple/.simplerc
    - name: Create a Test Script
      run: >
        new testing-new --template test
    - name: Run a Test Script
      run: >
        testing-new 
