name: Release kit.zip

on:
  push:
    branches:
      - main
      - beta
      - alpha
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: "YYYY-MM-DD-HH-mm-ss"

      - name: Checkout kit
        uses: actions/checkout@master

      - name: Set env vars
        run: |
          echo "kit_path=$PWD" >> $GITHUB_ENV

      - name: Bundle latest node
        run: >
          bash "${{ env.kit_path }}/install-node.sh" --prefix "${{ env.kit_path }}/node" --platform darwin

      - name: Add node to PATH
        run: |
          echo "${{ env.kit_path }}/node/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH

      - name: Run tests
        run: |
          cd "${{ env.kit_path }}"
          npm run test

      - name: npm install packages
        run: |
          cd "${{ env.kit_path }}"
          npm i

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          path: "${{ env.kit_path }}"
          filename: kit-${{ env.GITHUB_REF_SLUG_URL }}.zip
          exclusions: "*.git* *src/* *test/*"

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: kit-${{ env.GITHUB_REF_SLUG_URL }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
