name: Test Install, New Script, Run Script

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha
    tags:
      - "*"

jobs:
  install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    defaults:
      run:
        shell: bash
    steps:
      - name: Set env vars
        run: |
          echo "kit_path=~/.kit" >> $GITHUB_ENV
          echo "kenv_path=~/.kenv" >> $GITHUB_ENV

      - name: Extract Branch Name
        uses: rlespinasse/github-slug-action@3.1.0

      - name: Print event variables
        run: |
          echo "url: ${{ github.event.pull_request.url }}"

      - name: Log Ref Name
        run: echo "Running install from ${{ env.GITHUB_REF_SLUG }}"

      - name: Checkout kit
        uses: actions/checkout@master
        with:
          path: "${{ env.kit_path }}"
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout kenv
        uses: actions/checkout@master
        with:
          repository: johnlindquist/kenv
          path: "${{ env.kenv_path }}"

      - name: Install latest node and add to PATH
        run: |
          bash "${{ env.kit_path }}/install-node.sh" --prefix "${{ env.kit_path }}/node"
          echo "${{ env.kit_path }}/node/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH

      - name: npm install
        run: |
          cd "${{ env.kit_path }}"
          npm install

      - name: cat kit.sh
        run: cat "${{ env.kit_path }}/node/bin/script"

      - name: setup .kenv dir
        run: |
          cd "${{ env.kit_path }}"
          KENV="${{ env.kenv_path }}"" bash "${{ env.kit_path }}/script" "${{ env.kit_path }}/setup/setup.js"

      - name: list .kenv dir
        run: >
          ls ${{ env.kenv_path }}

      - name: View .profile
        run: >
          cat ~/.profile

      - name: View bin
        run: >
          cat "${{ env.kit_path }}/bin/kit"

      - name: View .env
        run: >
          cat "${{ env.kenv_path }}/.env"

      - name: Adding ~/.kit/bin to Path
        run: echo "${{ env.kit_path }}/bin" >> $GITHUB_PATH

      - name: Adding ~/.kenv/bin to Path
        run: echo "${{ env.kenv_path }}/bin" >> $GITHUB_PATH

      - name: Chmod ~/.kit/bin/kit
        run: chmod +x "${{ env.kit_path }}/bin/kit"

      - name: Create a Test Script
        run: >
          kit new running-test-template --template default

      - name: Run the Test Script
        run: >
          running-test-template --trust

      - name: Test kit script with new-and-rm
        run: |
          KENV="${{ env.kenv_path }}" KIT_TEMPLATE=default "${{ env.kit_path }}/script" "${{ env.kit_path }}/test/new-and-rm.js"
